### PR TITLE
[Enhancement] Integrate Prometheus and Grafana for monitoring in playground

### LINKED ISSUE #94: [Enhancement] Integrate Prometheus and Grafana for monitoring in playground
**Description**:  
To improve the project's observability and monitoring capabilities, it is suggested to integrate Prometheus and Grafana into the playground environment. This would enable easier monitoring of various application metrics.

**Objectives**:
- **Prometheus**: For collecting and storing application metrics.
- **Grafana**: For visualizing data collected by Prometheus, providing the team with real-time monitoring dashboards.

**Implementation Approach**:
- Add Prometheus and Grafana configurations within the Docker environment.
- Set up basic metrics collection, such as application request rate, response time, etc.

### PR DESCRIPTION
**Pull request by orenccl**
Closes #94 

1. **Add monitoring information to the README**
2. **Add Prometheus and Grafana settings to docker-compose**
3. **Add a basic Prometheus configuration file**
4. **Add a basic Grafana configuration, provision data source to Prometheus, and provision a dashboard to Gravitino Playground**
5. **Add port checks in `playground.sh`**

### Fixes
- Change `- 18888:8888` to `- "18888:8888"` in the docker-compose.yaml for correct port mapping format.
- Change `docker-compose ps` to `docker-compose ps -a` to view all containers (including stopped ones).

---

**Note**: Please ignore the high JVM Non-Heap Memory Usage and JVM Direct Memory Usage caused by my WSL2 environment.

image

### CODE REVIEW

**Comment by xunliu** [comment]
@orenccl 
Very coooool !!!!
Thank you for your contribution.

**Comment by FANNG1** [comment]
cool

**Review by FANNG1 — APPROVED** [review]

**Comment by orenccl** [comment]
At the first commit, gravitino-playground.json is a bit large(109KB).
This file is a preset for the Gravitino dashboard.
In the second commit, I reduced this file by minifying it, bringing the size down to 53KB (less than 50% of the original size).

## Why this file is so large

1. I included almost every metric provided by Gravitino so others don't have to create panels themselves.
2. The preset dashboard provided on the official website is even 378KB.  [[Node Exporter Full with Node Name | Grafana Labs](https://grafana.com/grafana/dashboards/10242-node-exporter-full/)]
Therefore, I think 53KB is reasonable given the level of detail in the dashboard.

Below is current look:

image (1)
image (4)
image (5)
image (6)
image (7)
image (8)

Hope 53KB is fine.
If not, I can reduce it further by removing rarely used metrics, like this.
image (2)

Alternatively, I can split it into three different dashboards; each one will be smaller, but the total size will remain the same.
image (3)

**Comment by orenccl** [comment]
@xunliu  I’d love to hear your perspective.

**Comment by orenccl** [comment]
Here’s an example of minified JSON for those who may not be familiar with it.

95b01da0-fab9-4fa3-aade-eb212a73a4d1-jsonformatter
Credit: https://devutils.com/guide/json-formattervalidator-7/

**Review by xunliu — DISMISSED** [review]
hi @orenccl 
Thank you for your contributions,
LGTM

**Comment by orenccl** [comment]
Hi @xunliu 

The home path has been configured to go directly to the Grafana dashboard.

**Review by xunliu — APPROVED** [review]
Good job!
LGTM.

**Pull request merged**
